### PR TITLE
Update AttestationRegistry.sol: Optimized 'For' loops

### PR DESCRIPTION
**Pull request by Aryan9592**
## What does this PR do?
This PR is solely aimed at reducing gas costs by enhancing the 'for' loops.

Fixes #
Changed the structure of 'for' loops. This will help -> https://gist.github.com/grGred/9bab8b9bad0cd42fc23d4e31e7347144#for-loops-improvement

Also, make a double-check whether that `unchecked` block doesn't create any unwanted bugs or errors.
However, `i++` to `++i` might won't be a problem.

### Type of change

- [ ] Chore
- [ ] Bug fix
- [ ] New feature
- [ ] Documentation update

## Check list

- [ ] Unit tests for any smart contract change
- [ ] Contracts and functions are documented

### CODE REVIEW

**Comment by alainncls** [comment]
Hey @Aryan9592 👋 
Thanks for your contribution to Verax (once again)!

I was running some comparative tests, and if I'm not mistaken, when running this new version of the `massImport` method, the difference is `136 gas`.
I feel like this is not a huge change for a degraded code readability, what do you think?

In any case, feel free to join us on Discord if you want to learn more about Verax or wish to contribute!

**Comment by Aryan9592** [comment]
Actually, solidity introduced these `unchecked` blocks right after the 0.8 version, and these types of changes are being used in various repositories and are now familiar to many devs out there. Still, if you find them not that good as compared to the readability factor, we can remove that `unchecked` block inside the `massImport` function. Won't be a big deal to revert some changes back. and changes like `uint256 i = 0;` -> `uint256 i;` and `i++` -> `++i` are quite common..
and talking about the gas difference, when these changes sum up they become really valuable sometimes..Maybe I be digging even more into this codebase

**Comment by Aryan9592** [comment]
> In any case, feel free to join us on Discord if you want to learn more about Verax or wish to contribute!

Send me the invite!

**Comment by orbmis** [comment]
@Aryan9592 : https://discord.gg/Sq4EmYdBEk

**Comment by alainncls** [comment]
Hey @Aryan9592 I didn't forget about this PR!
Instead of introducing `unchecked` blocks in the contracts, I created an external `uncheckedInc` function to call. in the loops.

The corresponding PR is there if you're interested: #350 
For example, when running the `massImport` function with 100 payloads, we decrease the gas cost by 0.04%.
I'm closing this PR in favor of #350 if that's OK with you.

**Comment by Aryan9592** [comment]
Yep that's great @alainncls

**Pull request closed without merging**
